#!/usr/bin/env python3
"""Bundle assets/buildings/*.json into docs/mockups/buildings.js.

The recipes are the source and the module is their transcription, the same
rule the marching cubes tables live under: one file that is read by the
mockup today and by the core tomorrow, and a script between them so the
two can never disagree. `--check` regenerates and compares.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "buildings"
OUT = ROOT / "docs" / "mockups" / "buildings.js"


def bundle():
    recipes = {}
    for path in sorted(SRC.glob("*.json")):
        with open(path, encoding="utf-8") as f:
            recipe = json.load(f)
        for key in ("name", "footprint", "storey", "storeys", "brushes"):
            if key not in recipe:
                sys.exit(f"{path.name}: missing {key}")
        if recipe["name"] != path.stem:
            sys.exit(f"{path.name}: name is {recipe['name']}")
        recipes[recipe["name"]] = recipe
    body = json.dumps(recipes, indent=1, ensure_ascii=True)
    return (
        "// GENERATED by tools/bundle_buildings.py from assets/buildings/*.json.\n"
        "// Edit the recipes, not this file; `--check` holds the two together.\n"
        f"export const BUILDINGS = {body};\n"
    )


def main():
    text = bundle()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            sys.exit(f"{OUT.relative_to(ROOT)} is stale: run tools/bundle_buildings.py")
        count = len(list(SRC.glob("*.json")))
        print(f"bundle: ok, {count} recipes")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
